modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/COMPANYNAMEHERE/TQuickSwap/issues"

[[mods]]
modId = "tquickswap"
version = "${version}"
displayName = "TQuickSwap"
authors = "TetraLights"
description = '''
Maintain two separate player profiles (Survival/Creative) and swap them with /swap.
'''

[[dependencies.tquickswap]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tquickswap]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.10,1.22)"
ordering = "NONE"
side = "BOTH"
